FROM node:latest
MAINTAINER Dermoumi S. <hi@sdrm.me>

# Install google chrome (and unzip)
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
 && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
 && apt-get update -qq \
 && apt-get install -y google-chrome-stable unzip --no-install-recommends
